using System.Collections;
using System.Collections.Generic;
using UnityEngine;


namespace HANA_ClipDatas
{
    public class HANA_ClipData
    {
        public static readonly Dictionary<string, string> clipNameTable_VRoidBeta = new Dictionary<string, string>()
        {
            {"BrowDownLeft",        "browDownLeft"},
            {"BrowDownRight",       "browDownRight"},
            {"BrowInnerUp",         "browInnerUp"},
            {"BrowOuterUpLeft",     "browOuterUpLeft"},
            {"BrowOuterUpRight",    "browOuterUpRight"},
            {"CheekPuff",           "cheekPuff"},
            {"CheekSquintLeft",     "cheekSquintLeft"},
            {"CheekSquintRight",    "cheekSquintRight"},
            {"EyeBlinkLeft",        "Face.M_F00_000_00_Fcl_EYE_Close_L"},
            {"EyeBlinkRight",       "Face.M_F00_000_00_Fcl_EYE_Close_R"},
            {"EyeLookDownLeft",     "eyeLookDownLeft"},
            {"EyeLookDownRight",    "eyeLookDownRight"},
            {"EyeLookInLeft",       "eyeLookInLeft"},
            {"EyeLookInRight",      "eyeLookInRight"},
            {"EyeLookOutLeft",      "eyeLookOutLeft"},
            {"EyeLookOutRight",     "eyeLookOutRight" },
            {"EyeLookUpLeft",       "eyeLookUpLeft"},
            {"EyeLookUpRight",      "eyeLookUpRight"},
            {"EyeSquintLeft",       "eyeSquintLeft"},
            {"EyeSquintRight",      "eyeSquintRight"},
            {"EyeWideLeft",         "eyeWideLeft"},
            {"EyeWideRight",        "eyeWideRight"},
            {"JawForward",          "jawForward"},
            {"JawLeft",             "jawLeft"},
            {"JawOpen",             "jawOpen"},
            {"JawRight",            "jawRight"},
            {"MouthClose",          "mouthClose"},
            {"MouthDimpleLeft",     "mouthDimpleLeft"},
            {"MouthDimpleRight",    "mouthDimpleRight"},
            {"MouthFrownLeft",      "mouthFrownLeft"},
            {"MouthFrownRight",     "mouthFrownRight"},
            {"MouthFunnel",         "mouthFunnel"},
            {"MouthLeft",           "mouthLeft"},
            {"MouthLowerDownLeft",  "mouthLowerDownLeft"},
            {"MouthLowerDownRight", "mouthLowerDownRight"},
            {"MouthPressLeft",      "mouthPressLeft"},
            {"MouthPressRight",     "mouthPressRight"},
            {"MouthPucker",         "mouthPucker"},
            {"MouthRight",          "mouthRight"},
            {"MouthRollLower",      "mouthRollLower"},
            {"MouthRollUpper",      "mouthRollUpper"},
            {"MouthShrugLower",     "mouthShrugLower"},
            {"MouthShrugUpper",     "mouthShrugUpper"},
            {"MouthSmileLeft",      "mouthSmileLeft"},
            {"MouthSmileRight",     "mouthSmileRight"},
            {"MouthStretchLeft",    "mouthStretchLeft"},
            {"MouthStretchRight",   "mouthStretchRight"},
            {"MouthUpperUpLeft",    "mouthUpperUpLeft"},
            {"MouthUpperUpRight",   "mouthUpperUpRight"},
            {"NoseSneerLeft",       "noseSneerLeft"},
            {"NoseSneerRight",      "noseSneerRight"},
            {"TongueOut",           "tongueOut"},
        };

        public static readonly Dictionary<string, string> clipNameTable_NewVRoid = new Dictionary<string, string>()
        {
            {"BrowDownLeft",        "browDownLeft"},
            {"BrowDownRight",       "browDownRight"},
            {"BrowInnerUp",         "browInnerUp"},
            {"BrowOuterUpLeft",     "browOuterUpLeft"},
            {"BrowOuterUpRight",    "browOuterUpRight"},
            {"CheekPuff",           "cheekPuff"},
            {"CheekSquintLeft",     "cheekSquintLeft"},
            {"CheekSquintRight",    "cheekSquintRight"},
            {"EyeBlinkLeft",        "Fcl_EYE_Close_L"},
            {"EyeBlinkRight",       "Fcl_EYE_Close_R"},
            {"EyeLookDownLeft",     "eyeLookDownLeft"},
            {"EyeLookDownRight",    "eyeLookDownRight"},
            {"EyeLookInLeft",       "eyeLookInLeft"},
            {"EyeLookInRight",      "eyeLookInRight"},
            {"EyeLookOutLeft",      "eyeLookOutLeft"},
            {"EyeLookOutRight",     "eyeLookOutRight" },
            {"EyeLookUpLeft",       "eyeLookUpLeft"},
            {"EyeLookUpRight",      "eyeLookUpRight"},
            {"EyeSquintLeft",       "eyeSquintLeft"},
            {"EyeSquintRight",      "eyeSquintRight"},
            {"EyeWideLeft",         "eyeWideLeft"},
            {"EyeWideRight",        "eyeWideRight"},
            {"JawForward",          "jawForward"},
            {"JawLeft",             "jawLeft"},
            {"JawOpen",             "jawOpen"},
            {"JawRight",            "jawRight"},
            {"MouthClose",          "mouthClose"},
            {"MouthDimpleLeft",     "mouthDimpleLeft"},
            {"MouthDimpleRight",    "mouthDimpleRight"},
            {"MouthFrownLeft",      "mouthFrownLeft"},
            {"MouthFrownRight",     "mouthFrownRight"},
            {"MouthFunnel",         "mouthFunnel"},
            {"MouthLeft",           "mouthLeft"},
            {"MouthLowerDownLeft",  "mouthLowerDownLeft"},
            {"MouthLowerDownRight", "mouthLowerDownRight"},
            {"MouthPressLeft",      "mouthPressLeft"},
            {"MouthPressRight",     "mouthPressRight"},
            {"MouthPucker",         "mouthPucker"},
            {"MouthRight",          "mouthRight"},
            {"MouthRollLower",      "mouthRollLower"},
            {"MouthRollUpper",      "mouthRollUpper"},
            {"MouthShrugLower",     "mouthShrugLower"},
            {"MouthShrugUpper",     "mouthShrugUpper"},
            {"MouthSmileLeft",      "mouthSmileLeft"},
            {"MouthSmileRight",     "mouthSmileRight"},
            {"MouthStretchLeft",    "mouthStretchLeft"},
            {"MouthStretchRight",   "mouthStretchRight"},
            {"MouthUpperUpLeft",    "mouthUpperUpLeft"},
            {"MouthUpperUpRight",   "mouthUpperUpRight"},
            {"NoseSneerLeft",       "noseSneerLeft"},
            {"NoseSneerRight",      "noseSneerRight"},
            {"TongueOut",           "tongueOut"},
        };

        public static readonly Dictionary<string, float> clipWeightTable_VRoid = new Dictionary<string, float>()
        {
            {"BrowDownLeft",        50.0f },
            {"BrowDownRight",       50.0f },
            {"BrowInnerUp",         50.0f },
            {"BrowOuterUpLeft",     50.0f },
            {"BrowOuterUpRight",    50.0f },
            {"CheekPuff",           50.0f },
            {"CheekSquintLeft",     50.0f },
            {"CheekSquintRight",    50.0f },
            {"EyeBlinkLeft",        100.0f },
            {"EyeBlinkRight",       100.0f },
            {"EyeLookDownLeft",     100.0f },
            {"EyeLookDownRight",    100.0f },
            {"EyeLookInLeft",       100.0f },
            {"EyeLookInRight",      100.0f },
            {"EyeLookOutLeft",      100.0f },
            {"EyeLookOutRight",     100.0f },
            {"EyeLookUpLeft",       100.0f },
            {"EyeLookUpRight",      100.0f },
            {"EyeSquintLeft",       90.0f },
            {"EyeSquintRight",      90.0f },
            {"EyeWideLeft",         100.0f },
            {"EyeWideRight",        100.0f },
            {"JawForward",          100.0f },
            {"JawLeft",             100.0f },
            {"JawOpen",             100.0f },
            {"JawRight",            100.0f },
            {"MouthClose",          100.0f },
            {"MouthDimpleLeft",     100.0f },
            {"MouthDimpleRight",    100.0f },
            {"MouthFrownLeft",      50.0f },
            {"MouthFrownRight",     50.0f },
            {"MouthFunnel",         100.0f },
            {"MouthLeft",           100.0f },
            {"MouthLowerDownLeft",  100.0f },
            {"MouthLowerDownRight", 100.0f },
            {"MouthPressLeft",      100.0f },
            {"MouthPressRight",     100.0f },
            {"MouthPucker",         50.0f },
            {"MouthRight",          100.0f },
            {"MouthRollLower",      50.0f },
            {"MouthRollUpper",      50.0f },
            {"MouthShrugLower",     100.0f },
            {"MouthShrugUpper",     100.0f },
            {"MouthSmileLeft",      50.0f },
            {"MouthSmileRight",     50.0f },
            {"MouthStretchLeft",    50.0f },
            {"MouthStretchRight",   50.0f },
            {"MouthUpperUpLeft",    100.0f },
            {"MouthUpperUpRight",   100.0f },
            {"NoseSneerLeft",       50.0f },
            {"NoseSneerRight",      50.0f },
            {"TongueOut",           100.0f },
        };

        public static readonly Dictionary<string, string> clipNameTable_def = new Dictionary<string, string>()
        {
            {"BrowDownLeft",        "browDownLeft"},
            {"BrowDownRight",       "browDownRight"},
            {"BrowInnerUp",         "browInnerUp"},
            {"BrowOuterUpLeft",     "browOuterUpLeft"},
            {"BrowOuterUpRight",    "browOuterUpRight"},
            {"CheekPuff",           "cheekPuff"},
            {"CheekSquintLeft",     "cheekSquintLeft"},
            {"CheekSquintRight",    "cheekSquintRight"},
            {"EyeBlinkLeft",        "eyeBlinkLeft"},
            {"EyeBlinkRight",       "eyeBlinkRight"},
            {"EyeLookDownLeft",     "eyeLookDownLeft"},
            {"EyeLookDownRight",    "eyeLookDownRight"},
            {"EyeLookInLeft",       "eyeLookInLeft"},
            {"EyeLookInRight",      "eyeLookInRight"},
            {"EyeLookOutLeft",      "eyeLookOutLeft"},
            {"EyeLookOutRight",     "eyeLookOutRight" },
            {"EyeLookUpLeft",       "eyeLookUpLeft"},
            {"EyeLookUpRight",      "eyeLookUpRight"},
            {"EyeSquintLeft",       "eyeSquintLeft"},
            {"EyeSquintRight",      "eyeSquintRight"},
            {"EyeWideLeft",         "eyeWideLeft"},
            {"EyeWideRight",        "eyeWideRight"},
            {"JawForward",          "jawForward"},
            {"JawLeft",             "jawLeft"},
            {"JawOpen",             "jawOpen"},
            {"JawRight",            "jawRight"},
            {"MouthClose",          "mouthClose"},
            {"MouthDimpleLeft",     "mouthDimpleLeft"},
            {"MouthDimpleRight",    "mouthDimpleRight"},
            {"MouthFrownLeft",      "mouthFrownLeft"},
            {"MouthFrownRight",     "mouthFrownRight"},
            {"MouthFunnel",         "mouthFunnel"},
            {"MouthLeft",           "mouthLeft"},
            {"MouthLowerDownLeft",  "mouthLowerDownLeft"},
            {"MouthLowerDownRight", "mouthLowerDownRight"},
            {"MouthPressLeft",      "mouthPressLeft"},
            {"MouthPressRight",     "mouthPressRight"},
            {"MouthPucker",         "mouthPucker"},
            {"MouthRight",          "mouthRight"},
            {"MouthRollLower",      "mouthRollLower"},
            {"MouthRollUpper",      "mouthRollUpper"},
            {"MouthShrugLower",     "mouthShrugLower"},
            {"MouthShrugUpper",     "mouthShrugUpper"},
            {"MouthSmileLeft",      "mouthSmileLeft"},
            {"MouthSmileRight",     "mouthSmileRight"},
            {"MouthStretchLeft",    "mouthStretchLeft"},
            {"MouthStretchRight",   "mouthStretchRight"},
            {"MouthUpperUpLeft",    "mouthUpperUpLeft"},
            {"MouthUpperUpRight",   "mouthUpperUpRight"},
            {"NoseSneerLeft",       "noseSneerLeft"},
            {"NoseSneerRight",      "noseSneerRight"},
            {"TongueOut",           "tongueOut"},
        };

        public static readonly Dictionary<string, float> clipWeightTable_def = new Dictionary<string, float>()
        {
            {"BrowDownLeft",        100.0f },
            {"BrowDownRight",       100.0f },
            {"BrowInnerUp",         100.0f },
            {"BrowOuterUpLeft",     100.0f },
            {"BrowOuterUpRight",    100.0f },
            {"CheekPuff",           100.0f },
            {"CheekSquintLeft",     100.0f },
            {"CheekSquintRight",    100.0f },
            {"EyeBlinkLeft",        100.0f },
            {"EyeBlinkRight",       100.0f },
            {"EyeLookDownLeft",     100.0f },
            {"EyeLookDownRight",    100.0f },
            {"EyeLookInLeft",       100.0f },
            {"EyeLookInRight",      100.0f },
            {"EyeLookOutLeft",      100.0f },
            {"EyeLookOutRight",     100.0f },
            {"EyeLookUpLeft",       100.0f },
            {"EyeLookUpRight",      100.0f },
            {"EyeSquintLeft",       100.0f },
            {"EyeSquintRight",      100.0f },
            {"EyeWideLeft",         100.0f },
            {"EyeWideRight",        100.0f },
            {"JawForward",          100.0f },
            {"JawLeft",             100.0f },
            {"JawOpen",             100.0f },
            {"JawRight",            100.0f },
            {"MouthClose",          100.0f },
            {"MouthDimpleLeft",     100.0f },
            {"MouthDimpleRight",    100.0f },
            {"MouthFrownLeft",      100.0f },
            {"MouthFrownRight",     100.0f },
            {"MouthFunnel",         100.0f },
            {"MouthLeft",           100.0f },
            {"MouthLowerDownLeft",  100.0f },
            {"MouthLowerDownRight", 100.0f },
            {"MouthPressLeft",      100.0f },
            {"MouthPressRight",     100.0f },
            {"MouthPucker",         100.0f },
            {"MouthRight",          100.0f },
            {"MouthRollLower",      100.0f },
            {"MouthRollUpper",      100.0f },
            {"MouthShrugLower",     100.0f },
            {"MouthShrugUpper",     100.0f },
            {"MouthSmileLeft",      100.0f },
            {"MouthSmileRight",     100.0f },
            {"MouthStretchLeft",    100.0f },
            {"MouthStretchRight",   100.0f },
            {"MouthUpperUpLeft",    100.0f },
            {"MouthUpperUpRight",   100.0f },
            {"NoseSneerLeft",       100.0f },
            {"NoseSneerRight",      100.0f },
            {"TongueOut",           100.0f },
        };

        public static readonly Dictionary<string, string> clipNameTable_SRanipal = new Dictionary<string, string>()
        {
            {"Cheek_Puff_Left",         "Cheek_Puff_Left"},
            {"Cheek_Puff_Right",        "Cheek_Puff_Right"},
            {"Cheek_Suck",              "Cheek_Suck"},
            {"Eye_Frown",               "Eye_Frown"},
            {"Eye_Left_Blink",          "Eye_Left_Blink"},
            {"Eye_Left_Down",           "Eye_Left_Down"},
            {"Eye_Left_Left",           "Eye_Left_Left"},
            {"Eye_Left_Right",          "Eye_Left_Right"},
            {"Eye_Left_squeeze",        "Eye_Left_squeeze"},
            {"Eye_Left_Up",             "Eye_Left_Up"},
            {"Eye_Left_Wide",           "Eye_Left_Wide"},
            {"Eye_Right_Blink",         "Eye_Right_Blink"},
            {"Eye_Right_Down",          "Eye_Right_Down"},
            {"Eye_Right_Left",          "Eye_Right_Left"},
            {"Eye_Right_Right",         "Eye_Right_Right"},
            {"Eye_Right_squeeze",       "Eye_Right_squeeze"},
            {"Eye_Right_Up",            "Eye_Right_Up"},
            {"Eye_Right_Wide",          "Eye_Right_Wide"},
            {"Jaw_Forward",             "Jaw_Forward"},
            {"Jaw_Left",                "Jaw_Left"},
            {"Jaw_Open",                "Jaw_Open"},
            {"Jaw_Right",               "Jaw_Right"},
            {"Mouth_Ape_Shape",         "Mouth_Ape_Shape"},
            {"Mouth_Lower_DownLeft",    "Mouth_Lower_DownLeft"},
            {"Mouth_Lower_DownRight",   "Mouth_Lower_DownRight"},
            {"Mouth_Lower_Inside",      "Mouth_Lower_Inside"},
            {"Mouth_Lower_Left",        "Mouth_Lower_Left"},
            {"Mouth_Lower_Overlay",     "Mouth_Lower_Overlay"},
            {"Mouth_Lower_Overturn",    "Mouth_Lower_Overturn"},
            {"Mouth_Lower_Right",       "Mouth_Lower_Right"},
            {"Mouth_Pout",              "Mouth_Pout"},
            {"Mouth_Sad_Left",          "Mouth_Sad_Left"},
            {"Mouth_Sad_Right",         "Mouth_Sad_Right"},
            {"Mouth_Upper_Left",        "Mouth_Upper_Left"},
            {"Mouth_Upper_Overturn",    "Mouth_Upper_Overturn"},
            {"Mouth_Upper_Right",       "Mouth_Upper_Right"},
            {"Mouth_Upper_UpLeft",      "Mouth_Upper_UpLeft"},
            {"Mouth_Upper_UpRight",     "Mouth_Upper_UpRight"},
            {"Tongue_Down",             "Tongue_Down"},
            {"Tongue_DownLeft_Morph",   "Tongue_DownLeft_Morph"},
            {"Tongue_DownRight_Morph",  "Tongue_DownRight_Morph"},
            {"Tongue_Left",             "Tongue_Left"},
            {"Tongue_LongStep1",        "Tongue_LongStep1"},
            {"Tongue_LongStep2",        "Tongue_LongStep2"},
            {"Tongue_Right",            "Tongue_Right"},
            {"Tongue_Roll",             "Tongue_Roll"},
            {"Tongue_Up",               "Tongue_Up"},
            {"Tongue_UpLeft_Morph",     "Tongue_UpLeft_Morph"},
            {"Tongue_UpRight_Morph",    "Tongue_UpRight_Morph"},
        };
        public static readonly Dictionary<string, float> clipWeightTable_SRanipal = new Dictionary<string, float>()
        {
            {"Cheek_Puff_Left",         100.0f},
            {"Cheek_Puff_Right",        100.0f},
            {"Cheek_Suck",              100.0f},
            {"Eye_Frown",               100.0f},
            {"Eye_Left_Blink",          100.0f},
            {"Eye_Left_Down",           100.0f},
            {"Eye_Left_Left",           100.0f},
            {"Eye_Left_Right",          100.0f},
            {"Eye_Left_squeeze",        100.0f},
            {"Eye_Left_Up",             100.0f},
            {"Eye_Left_Wide",           100.0f},
            {"Eye_Right_Blink",         100.0f},
            {"Eye_Right_Down",          100.0f},
            {"Eye_Right_Left",          100.0f},
            {"Eye_Right_Right",         100.0f},
            {"Eye_Right_squeeze",       100.0f},
            {"Eye_Right_Up",            100.0f},
            {"Eye_Right_Wide",          100.0f},
            {"Jaw_Forward",             100.0f},
            {"Jaw_Left",                100.0f},
            {"Jaw_Open",                100.0f},
            {"Jaw_Right",               100.0f},
            {"Mouth_Ape_Shape",         100.0f},
            {"Mouth_Lower_DownLeft",    100.0f},
            {"Mouth_Lower_DownRight",   100.0f},
            {"Mouth_Lower_Inside",      100.0f},
            {"Mouth_Lower_Left",        100.0f},
            {"Mouth_Lower_Overlay",     100.0f},
            {"Mouth_Lower_Overturn",    100.0f},
            {"Mouth_Lower_Right",       100.0f},
            {"Mouth_Pout",              100.0f},
            {"Mouth_Sad_Left",          100.0f},
            {"Mouth_Sad_Right",         100.0f},
            {"Mouth_Upper_Left",        100.0f},
            {"Mouth_Upper_Overturn",    100.0f},
            {"Mouth_Upper_Right",       100.0f},
            {"Mouth_Upper_UpLeft",      100.0f},
            {"Mouth_Upper_UpRight",     100.0f},
            {"Tongue_Down",             100.0f},
            {"Tongue_DownLeft_Morph",   100.0f},
            {"Tongue_DownRight_Morph",  100.0f},
            {"Tongue_Left",             100.0f},
            {"Tongue_LongStep1",        100.0f},
            {"Tongue_LongStep2",        100.0f},
            {"Tongue_Right",            100.0f},
            {"Tongue_Roll",             100.0f},
            {"Tongue_Up",               100.0f},
            {"Tongue_UpLeft_Morph",     100.0f},
            {"Tongue_UpRight_Morph",    100.0f},
        };


        public static readonly string[,] sranipalBindNames_vroidBeta = new string[,]
        {
            { "Eye_Left_Blink", "Face.M_F00_000_00_Fcl_EYE_Close_L", "Brow_Left_Blink"},
            { "Eye_Right_Blink", "Face.M_F00_000_00_Fcl_EYE_Close_R", "Brow_Right_Blink"},
        };
        public static readonly string[,] sranipalBindNames_newVRoid = new string[,]
        {
            { "Eye_Left_Blink", "Fcl_EYE_Close_L", "Brow_Left_Blink"},
            { "Eye_Right_Blink", "Fcl_EYE_Close_R", "Brow_Right_Blink"},
        };
    }
}
